# Generated by Django 3.2.16 on 2023-01-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='start_time',
        ),
    ]
