# Generated by Django 3.2.16 on 2023-01-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20230112_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_cronjob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='valid_duration',
            field=models.IntegerField(default=5),
        ),
    ]
