# Generated by Django 4.1.5 on 2023-01-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='detail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
