# Generated by Django 3.2.16 on 2023-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
